### ISSUE TITLE
Not unsubscribing from Redis channel on crash

### ISSUE THREAD

**Issue by cngc4e** [cngc4e/DiscordCow#1]
To reproduce, switch off wifi while the bot is running.
```
29/11/21 17:09 ERROR InfraConn [SUB] A Redis client error occured: Error: read ECONNRESET
29/11/21 17:09 ERROR InfraConn [SUB] A Redis client error occured: Error: connect EHOSTUNREACH -censored-
29/11/21 17:09 ERROR InfraConn [SUB] A Redis client error occured: Error: connect EHOSTUNREACH -censored-
29/11/21 17:09 ERROR InfraConn [SUB] A Redis client error occured: Error: Cannot send commands in PubSub mode
node_modules\redis\dist\lib\client\commands-queue.js:234
        throw new Error('Got an unexpected reply from Redis');
        ^

Error: Got an unexpected reply from Redis
    at RedisCommandsQueue._RedisCommandsQueue_shiftWaitingForReply (node_modules\redis\dist\lib\client\commands-queue.js:234:15)
    at JavascriptRedisParser.returnError (node_modules\redis\dist\lib\client\commands-queue.js:65:142)
    at JavascriptRedisParser.execute (node_modules\redis-parser\lib\parser.js:542:14)
    at RedisCommandsQueue.parseResponse (node_s\redis\dist\lib\client\commands-queue.js:179:71)
    at RedisSocket.<anonymous> (node_modules\redis\dist\lib\client\index.js:339:83)
    at RedisSocket.emit (node:events:390:28)
    at Socket.<anonymous> (node_modules\redis\dist\lib\client\socket.js:177:44)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
```

after `npm start`
```
29/11/21 17:16 INFO The following optional environment variables have been loaded: BOT_OWNERS, BOT_LOCALE, BOT_TIMEZONE, BOT_COMMANDS_PATHS, BOT_LISTENERS_PATHS, REDIS_URL
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Attempt to listen on channel :receiver/discord:ChokeOnWater which already had 1 subscribers. Duplicated process... or hacked?".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

**Comment by cngc4e** [comment]
What's also pretty weird is that [PUB] should've complained about the connection reset too, but there are only logs about [SUB].
